---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/driver-records":
    get:
      summary: Retrieves all driver records
      tags:
      - Driver Records
      responses:
        '200':
          description: driver records found
          content:
            application/json:
              examples:
                response:
                  value:
                  - driving_licence_number: CASE0507TEAA
                    first_names: Tench
                    last_name: Casey
                    date_of_birth: '1995-05-07'
                    driving_licence_type: Provisional
              schema:
                type: array
                items:
                  "$ref": "#/components/schemas/driver_record"
    post:
      summary: Create a driver record
      tags:
      - Driver Records
      parameters: []
      responses:
        '201':
          description: driver record created
          content:
            application/json:
              examples:
                with_licence_number:
                  value:
                    driving_licence_number: GILE1012JUXM
                    first_names: Julia Suzanne
                    last_name: Giles
                    date_of_birth: '2001-10-12'
                    driving_licence_type: Provisional
                without_licence_number:
                  value:
                    first_names: Julia Suzanne
                    last_name: Giles
                    date_of_birth: '2001-10-12'
                    driving_licence_type: Provisional
              schema:
                oneOf:
                - "$ref": "#/components/schemas/driver_record"
                - "$ref": "#/components/schemas/driver_record_without_driving_licence_number"
        '400':
          description: bad request body
        '409':
          description: driver licence number conflict
        '422':
          description: record invalid
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
              - "$ref": "#/components/schemas/driver_record"
              - "$ref": "#/components/schemas/driver_record_without_driving_licence_number"
  "/driver-records/{driving_licence_number}":
    get:
      summary: Retrieves a driver record
      tags:
      - Driver Records
      parameters:
      - name: driving_licence_number
        in: path
        example: CASE0507TEAA
        required: true
        schema:
          type: string
      responses:
        '200':
          description: driver record found
          content:
            application/json:
              examples:
                response:
                  value:
                    driving_licence_number: CASE0507TEAA
                    first_names: Tench
                    last_name: Casey
                    date_of_birth: '1995-05-07'
                    driving_licence_type: Full
              schema:
                "$ref": "#/components/schemas/driver_record"
        '404':
          description: driver record not found
    put:
      summary: Updates a driver record
      tags:
      - Driver Records
      parameters:
      - name: driving_licence_number
        in: path
        example: CASE0507TEAA
        required: true
        schema:
          type: string
      responses:
        '200':
          description: driver record updated
          content:
            application/json:
              examples:
                all_possible_fields:
                  value:
                    first_names: Trent
                    last_name: Comet
                    driving_licence_type: Full
                just_driving_licence_type:
                  value:
                    driving_licence_type: Full
                just_first_names:
                  value:
                    first_names: Trent
                just_last_name:
                  value:
                    last_name: Comet
              schema:
                "$ref": "#/components/schemas/driver_record"
        '400':
          description: parameter missing
        '404':
          description: driver record not found
        '422':
          description: invalid data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_names:
                  type: string
                  example: Trent
                last_name:
                  type: string
                  example: Comet
                driving_licence_type:
                  type: string
                  example: Full
    delete:
      summary: Deletes a driver record
      tags:
      - Driver Records
      parameters:
      - name: driving_licence_number
        in: path
        example: PARK0404DASK
        required: true
        schema:
          type: string
      responses:
        '204':
          description: driver record deleted
          content:
            application/json:
              examples:
                example:
                  value:
                    first_names: David
                    last_name: Parker
                    date_of_birth: '2005-04-04'
        '400':
          description: parameter missing
        '404':
          description: driver record not found
        '409':
          description: driver record does not match
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_names:
                  type: string
                  example: David
                last_name:
                  type: string
                  example: Parker
                date_of_birth:
                  type: string
                  format: date
                  example: '2005-04-04'
              required:
              - first_names
              - last_name
              - date_of_birth
components:
  schemas:
    driver_record:
      type: object
      properties:
        driving_licence_number:
          type: string
          example: JONE1012FRIS
        first_names:
          type: string
          minLength: 1
          maxLength: 32
          example: Fred
        last_name:
          type: string
          minLength: 1
          maxLength: 32
          example: Jones
        date_of_birth:
          type: string
          format: date
          example: '1999-10-12'
        driving_licence_type:
          type: string
          enum:
          - Full
          - Provisional
      required:
      - first_names
      - last_name
      - date_of_birth
      - driving_licence_type
    driver_record_without_driving_licence_number:
      type: object
      properties:
        first_names:
          type: string
          minLength: 1
          maxLength: 32
          example: Fred
        last_name:
          type: string
          minLength: 1
          maxLength: 32
          example: Jones
        date_of_birth:
          type: string
          format: date
          example: '1999-10-12'
        driving_licence_type:
          type: string
          enum:
          - Full
          - Provisional
      required:
      - first_names
      - last_name
      - date_of_birth
      - driving_licence_type
      additionalProperties: false
servers:
- url: http://localhost:3000
